/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SalePoint;

import SalePoint.MasaDB;
import SalePoint.SellingProduct;
import static SalePoint.MakingSale.createSellProduct;
import static SalePoint.MakingSale.listProduct;
import static SalePoint.MakingSale.totalPrice;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lb19000961
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        txtDate.setText(setDate());
        txtTime.setText(setTime());
        
    }
    
    public void setUsername(String username){
        usernamehere.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTendered = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtChange = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAddCode = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        txtTotalProductPrice = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        sellBtn = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        resultslLabel = new javax.swing.JLabel();
        recietPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        boughtTbl = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        usernamehere = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        checkBtn = new javax.swing.JButton();
        txtProductName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 0), null, null));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("sub-total");

        txtSubTotal.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtSubTotal.setBorder(null);
        txtSubTotal.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtSubTotal.setName(""); // NOI18N
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("tax: 12%");

        txtTotal.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtTotal.setBorder(null);
        txtTotal.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtTotal.setName(""); // NOI18N
        txtTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalMouseClicked(evt);
            }
        });
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total-Amount");

        txtTendered.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtTendered.setBorder(null);
        txtTendered.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtTendered.setName(""); // NOI18N
        txtTendered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenderedActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("tendered cash:");

        txtChange.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtChange.setBorder(null);
        txtChange.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtChange.setName(""); // NOI18N
        txtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChangeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("change");

        txtAddCode.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtAddCode.setBorder(null);
        txtAddCode.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtAddCode.setName(""); // NOI18N
        txtAddCode.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtAddCodeInputMethodTextChanged(evt);
            }
        });
        txtAddCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddCodeActionPerformed(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtPrice.setText("50.00");
        txtPrice.setBorder(null);
        txtPrice.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtPrice.setName(""); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter product code here");

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Product price");

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Qantity");

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total product price");

        txtQuantity.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtQuantity.setBorder(null);
        txtQuantity.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtQuantity.setName(""); // NOI18N

        txtTotalProductPrice.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtTotalProductPrice.setBorder(null);
        txtTotalProductPrice.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtTotalProductPrice.setName(""); // NOI18N
        txtTotalProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalProductPriceActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 153, 255));
        addBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.setBorder(null);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        removeBtn.setBackground(new java.awt.Color(255, 0, 51));
        removeBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBtn.setText("Remove");
        removeBtn.setBorder(null);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        sellBtn.setBackground(new java.awt.Color(0, 153, 0));
        sellBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        sellBtn.setForeground(new java.awt.Color(255, 255, 255));
        sellBtn.setText("Sell");
        sellBtn.setBorder(null);
        sellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellBtnActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtSearch.setText("search");
        txtSearch.setBorder(null);
        txtSearch.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtSearch.setName(""); // NOI18N

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search for product code here:");

        resultslLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        resultslLabel.setForeground(new java.awt.Color(255, 255, 255));
        resultslLabel.setText("results here");

        recietPanel.setBackground(new java.awt.Color(153, 153, 0));

        boughtTbl.setBackground(java.awt.SystemColor.control);
        boughtTbl.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        boughtTbl.setForeground(new java.awt.Color(102, 102, 0));
        boughtTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produce code", "Product name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        boughtTbl.setGridColor(new java.awt.Color(153, 153, 0));
        boughtTbl.setRowHeight(25);
        boughtTbl.setRowMargin(4);
        jScrollPane1.setViewportView(boughtTbl);

        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Product list");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Time:");

        txtTime.setBackground(new java.awt.Color(204, 204, 0));
        txtTime.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setText("time");
        txtTime.setBorder(null);
        txtTime.setName(""); // NOI18N
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });

        txtDate.setBackground(new java.awt.Color(204, 204, 0));
        txtDate.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setText("date");
        txtDate.setBorder(null);
        txtDate.setName(""); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date:");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log out");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        usernamehere.setBackground(new java.awt.Color(102, 102, 0));
        usernamehere.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        usernamehere.setForeground(new java.awt.Color(0, 153, 204));
        usernamehere.setText("time");
        usernamehere.setBorder(null);
        usernamehere.setName(""); // NOI18N
        usernamehere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamehereActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\lebog\\Downloads\\New folder\\icons8-administrator-male-40.png")); // NOI18N

        jLabel13.setFont(new java.awt.Font("Ink Free", 1, 48)); // NOI18N
        jLabel13.setText("MASA GENERAL DEALER");

        javax.swing.GroupLayout recietPanelLayout = new javax.swing.GroupLayout(recietPanel);
        recietPanel.setLayout(recietPanelLayout);
        recietPanelLayout.setHorizontalGroup(
            recietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recietPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(recietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recietPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recietPanelLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(recietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recietPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recietPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(usernamehere, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        recietPanelLayout.setVerticalGroup(
            recietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recietPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(recietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(recietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addGap(62, 62, 62)
                .addComponent(jLabel13)
                .addGap(34, 34, 34)
                .addGroup(recietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(recietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernamehere, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        recietPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jLabel12, usernamehere});

        checkBtn.setBackground(new java.awt.Color(255, 255, 0));
        checkBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        checkBtn.setText("Check");
        checkBtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBtnStateChanged(evt);
            }
        });
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtProductName, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                            .addComponent(txtAddCode))
                                        .addGap(18, 18, 18)
                                        .addComponent(checkBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotalProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                            .addComponent(txtQuantity)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultslLabel)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(txtChange)
                    .addComponent(sellBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSubTotal)
                    .addComponent(txtTotal)
                    .addComponent(txtTendered)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(recietPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBtn, removeBtn, sellBtn});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(txtAddCode)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(checkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtTendered, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel7)
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txtTotalProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addComponent(sellBtn)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultslLabel)
                        .addGap(226, 226, 226))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(recietPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addBtn, removeBtn, sellBtn});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtChange, txtPrice, txtQuantity, txtSubTotal, txtTendered, txtTotal});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static String setDate(){ //method to get time
        
        LocalDate ate = LocalDate.now();
        String date = ate.toString();
        
       
     
        return date;
    }
     public static String setTime(){ //method to get date 
        LocalTime ime = LocalTime.now();
        
        String time = ime.toString();
        
       
     
        return time;
    } 
    String dat = setDate();
    
    public void registerLogout(String loguser){ // this method writes to a log file when they log out
         try{
            //creting a file write with file name
            
            
             BufferedWriter logfw = new BufferedWriter(new FileWriter("C:\\Users\\lebog\\OneDrive - biust.ac.bw\\Desktop\\login-regitser.txt", true)); //this will write to the cashier log
            
            String details1 = " MASA GENERAL DEALER \n     Fax:3314256 \n    Cell: 72187246 \n lebogangbilli@gmail.com \n \n"; //writing the store name
            logfw.append("\n user "+loguser+" log out! time :"+setTime()+"  date:"+setDate()); //appendin detail of log out
            logfw.append("\n ***************************************************\n");
            logfw.close(); //closing the file
        
        }
        catch(IOException e){ //catching the errors if the it fails to update
            e.printStackTrace();
            System.out.println("Not able to write into the file");
        }   
    }
    
   
    
    
    SellingProduct prod1; //declaring a product do initialisa everytime the product to sell is being created get added this one goes to reciet
      
    ArrayList<SellingProduct> list1 =new ArrayList<>(); //declaring a list to add product
    
    SoldProducts newsold; //declaring an new sold product to initialise everytime the product is created  this one goes to db
    
    ArrayList <SoldProducts> stockSold = new ArrayList<>(); //declariing and array to add sold stock here when add/sell button is clicked button
   
   //this method creats a new product has been sold
   public SoldProducts createSoldProduct(String code, int quan, double total, String date){
       SoldProducts newSoldProduct = new SoldProducts(code,quan,total,date); //create a new oject with the parameters
       return newSoldProduct;
   }
    
    public void display( ){ //this metthod populates the table with product    
       ArrayList<SellingProduct> pList = list1; //creates a selling prices  
       
        DefaultTableModel model = (DefaultTableModel)boughtTbl.getModel(); //creates a model   
       
       Object[] row = new Object[4];
       for(int i=0; i<pList.size(); i++){ //creating and setting table rows
           
           row[0] = pList.get(i).getProductCode();
           row[1] = pList.get(i).getProductName();        
           row[2] = pList.get(i).getQuantity();
           row[3] = pList.get(i).getProductPrice();  
           
           model.addRow(row);
       }

    }
    public void clearTable(){
       DefaultTableModel model = (DefaultTableModel)boughtTbl.getModel();
       model.setRowCount(0);
       
    }
    
    //this method will write to the file called recient talts the array od products, anount anf other details of the reciet
    public void printOutReciept(ArrayList<SellingProduct> prods, String cashier, double totalAmount, double cusChange, double cashTendered){
        
        //to try and write int the reciet
        
        try{
            //creting a file write with file name
            FileWriter fw = new FileWriter("C:\\Users\\lebog\\OneDrive - biust.ac.bw\\Desktop\\reciet.txt");
            
             BufferedWriter logfw = new BufferedWriter(new FileWriter("C:\\Users\\lebog\\OneDrive - biust.ac.bw\\Desktop\\cashierlog.txt", true)); //this will write to the cashier log
            
            String details1 = " MASA GENERAL DEALER \n     Fax:3314256 \n    Cell: 72187246 \n lebogangbilli@gmail.com \n \n"; //writing the store name
            
            
            fw.write(details1);
            logfw.append("**************************************\n"+details1);
            for(SellingProduct prod: prods){ //writing the products that have been bought by the customer
                fw.write(prod.toString() + "\n");
                logfw.append(prod.toString() + "\n");
            
            }
            //writting the total amount,change and the cash that was recieved frome the customer
            fw.write("\n Total amount: "+totalAmount+"\n"); 
            fw.write("\n cash tendered : "+cashTendered+"\n");
            fw.write("\n Change is: "+cusChange+"\n");
            fw.write(" \n Date: "+setDate()+ "  Time :"+setTime()+" \n");                   
            fw.write("Cashier name: "+cashier +"\n");
            
           
            
            
            logfw.append("\n Total amount: "+totalAmount+"\n"); 
            logfw.append("\n cash tendered : "+cashTendered+"\n");
            logfw.append("\n Change is: "+cusChange+"\n");
            logfw.append(" \n Date: "+setDate()+ "  Time :"+setTime()+" \n");
            logfw.append("Cashier name: "+cashier +"\n");
            
            
             fw.close();
            logfw.close();
        
        }
        
        
        catch(IOException e){ //catching the errors if the it fails to update
            e.printStackTrace();
            System.out.println("Not able to write into the file");
        }
       
    }
    public void addToSold(SoldProducts soldList){ // method adds the sold productto the db
        MasaDB addtosold = new MasaDB();
        addtosold.connectDB();
        
        
            if(addtosold.addToSoldStock(soldList)){ //adding the product to sold stock if error happens else block is ran
                System.out.println("product has been added successfully to sold stock.");
            }
            else{
                System.out.println("there was problem adding the product to sold.");
            }
        
        
    }
    
    
    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtTenderedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenderedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenderedActionPerformed

    private void txtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChangeActionPerformed

    private void txtAddCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddCodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtAddCodeActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtTotalProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalProductPriceActionPerformed

    public double calculateTotalPrice(){
         double totalprice; //declaring total
        totalprice = totalPrice(list1); //passing the list array into the method to calculate total
        txtSubTotal.setText(Double.toString(totalprice));
        double total = (totalprice+totalprice*0.14);
        
        return total;
    
    }
    
    
    public void sell(){
        
        DecimalFormat df = new DecimalFormat("0.00"); // seeting some format
         
        String cashier = usernamehere.getText();
      
        double total  = calculateTotalPrice();
       
        String ttl = df.format(total);
        txtTotal.setText(ttl);
  
       String txttendered = txtTendered.getText(); // getting the tendered cash
       double tendered = Double.parseDouble(txttendered); //converting to correct type to work with
       
       
       if(tendered>total){ //check if tendered cash is valid
           
            double change = tendered - total; //calculating change
            String chng = df.format(change); //formating and converting
            txtChange.setText(chng); //setting the text filed to show change
       
            printOutReciept(list1,cashier, total, change, tendered );
             
           printingProducts(list1); // printing to console the list of added products
       
           list1.clear();
           
       }
       else{
           showMessageDialog(null,"Please enter a valid tendered amount");
           
          
       }
       
    
    }
    
    public void printingProducts(ArrayList<SellingProduct> prods){
        
        for(SellingProduct prod: prods){
            System.out.println(prod.toString());
        }
        
    }
    
    public void reset (){
        
        //,ethod to reset all test fields
            txtAddCode.setText("");
           // txtChange.setText("");
        
            txtPrice.setText("");
            txtProductName.setText("");
            txtQuantity.setText("");
            
            txtSubTotal.setText("");
            txtTendered.setText("");
            
            txtTotal.setText("");
            txtTotalProductPrice.setText("");
            
        
    
    
    }
    
    
    private void sellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellBtnActionPerformed
        // TODO add your handling code here:
        
        if(list1.size()>0){ // can only if you have added products
            sell(); //calling the sell method
       
            printingProducts(list1); // to check if the array has bee cleared for next transaction
       
       
            reset();// to implemet when able to display the the total without having to tap on the button
        
        }
        else{
            showMessageDialog(null," Please add some product to sell");
        }
        
   
        
      
       
     
       
       
    }//GEN-LAST:event_sellBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBtnActionPerformed


    
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
     
        DecimalFormat df = new DecimalFormat("0.00");
        //getting the text input
        String code = txtAddCode.getText();
        String name = txtProductName.getText();
        String quan = txtQuantity.getText();
        String prce = txtPrice.getText();
        
        
        if(quan.isBlank() || Integer.parseInt(quan) < 1){ //setting the quantity to one if the value isn ot set by the seller/cashier
            quan = "1";
        }
        //coverting to approriate type
        int quantity = Integer.parseInt(quan);
        double price = Double.parseDouble(prce);
        
        double totalProdPrice = quantity*price; //
        String ttp = df.format(totalProdPrice); //formating and covering
        
        txtTotalProductPrice.setText(ttp); //setting the total product price

      
        prod1 = createSellProduct(code,name,price,quantity); //passing the input into the object
        newsold = createSoldProduct(code, quantity, totalProdPrice, setDate()); // creating the sold product to add to db
        
        addToSold(newsold); //add the currect product processed to the stock sold stock array that will be added to db by sell btn
        
             
        list1.add(prod1); //addig the ject int the array
       
   
        
        //clear fields after you add
        txtAddCode.setText("");
        txtQuantity.setText("");
        txtPrice.setText("");
        txtAddCode.hasFocus();
        display();
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
         //confirminng log out
          int conf = JOptionPane.showConfirmDialog(null,"You are about to be logged out", "confirm logout!", JOptionPane.DEFAULT_OPTION);
        // 0=ok
        if (conf == 0){
            Login in = new Login(); //creating a login screen object
            String cashier  = usernamehere.getText();// gettin the value of logged in user
            registerLogout(cashier); //registering the log in to the file
            this.dispose();// diposing the screen
            in.show();
        }
         
         
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void usernamehereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamehereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamehereActionPerformed

    private void txtAddCodeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtAddCodeInputMethodTextChanged
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_txtAddCodeInputMethodTextChanged

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        // TODO add your handling code here:
        clearTable();
         MasaDB gettinProduct = new MasaDB();
        gettinProduct.connectDB();
        
        String inputCode = txtAddCode.getText().toString();
        
        SellingProduct prodToSell = gettinProduct.getSellProduct(inputCode);
        
        txtPrice.setText(Double.toString(prodToSell.getProductPrice()));
        txtProductName.setText(prodToSell.getProductName());
        
    }//GEN-LAST:event_checkBtnActionPerformed

    private void checkBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBtnStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBtnStateChanged

    private void txtTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalMouseClicked
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("0.00"); // seeting some format
      
        double total  = calculateTotalPrice();
        
        String ttl = df.format(total);
        txtTotal.setText(ttl);
        
    }//GEN-LAST:event_txtTotalMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        ArrayList<SellingProduct> list1 =new ArrayList<>();
    

        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTable boughtTbl;
    private javax.swing.JButton checkBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel recietPanel;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel resultslLabel;
    private javax.swing.JButton sellBtn;
    private javax.swing.JTextField txtAddCode;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTendered;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalProductPrice;
    private javax.swing.JTextField usernamehere;
    // End of variables declaration//GEN-END:variables
}
